### ISSUE TITLE
Search Ignores Dest. IP Field

### ISSUE THREAD

**Issue by lexxua** [sipcapture/homer-api#20]
When i try to make Search using both fields Source IP and Dest IP. Resulting page ignores Dest ip.
Actually browser sends data as a post request but seems that field is ignored.
That I see in Chrome Debug:
curl 'http://webhomer.co.volia.com/api/profile/store/search' -H 'Pragma: no-cache' -H 'Origin: http://webhomer.co.volia.com' -H 'Accept-Encoding: gzip, deflate' -H 'Accept-Language: ru,en-US;q=0.8,en;q=0.6' -H 'User-Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_8_5) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/43.0.2357.130 Safari/537.36' -H 'Content-Type: application/json;charset=UTF-8' -H 'Accept: application/json, text/plain, _/_' -H 'Cache-Control: no-cache' -H 'Referer: http://webhomer.co.volia.com/' -H 'Cookie: VISITORID=848416697; __utma=56072236.2042610939.1412169153.1422954601.1433229510.27; __utmz=56072236.1415003501.13.2.utmcsr=google|utmccn=(organic)|utmcmd=organic|utmctr=(not%20provided); _ga=GA1.2.2042610939.1412169153; checkcookie=true; HOMERSESSID=vpikhfb0baml2m49hrilrbtmo7' -H 'Connection: keep-alive' --data-binary '{"id":"search","param":{"destion_ip":"77.120.8.192","source_ip":"77.120.8.178","ruri_user":"","from_user":""}}' --compressed

And here Homer`s SQL request :
SELECT t.id, date, (micro_ts DIV 1000) as milli_ts, micro_ts,method,reply_reason,ruri,ruri_user,ruri_domain,from_user,from_domain,from_tag,
to_user,to_domain,to_tag,pid_user,contact_user,auth_user,callid,callid_aleg,via_1,via_1_branch,cseq,diversion,reason,content_type,auth,
user_agent,source_ip,source_port,destination_ip,destination_port,contact_ip,contact_port,originator_ip,originator_port,correlation_id,proto,family,rtp_stat,type,node, 'call' as trans, 'single' as dbnode, hcs.alias as source_alias, hcd.alias as destination_alias FROM sip_capture_call_20150703 as t LEFT JOIN homerv5.alias as hcs ON t.source_ip=hcs.ip AND t.source_port=hcs.port LEFT JOIN homerv5.alias as hcd ON t.destination_ip=hcd.ip AND t.destination_port=hcd.port WHERE (t.date BETWEEN FROM_UNIXTIME(1435920105) AND FROM_UNIXTIME(1436276506)) AND ( source_ip = '77.120.8.178') order by t.id DESC LIMIT 200

Maybe I missed something in configuration ?

Thank you.

**Comment by adubovikov** [comment]
fixed
https://github.com/sipcapture/homer-ui/commit/9b6fa4b8a69bf4b33570968a33658c7378c17aa9

**Comment by lexxua** [comment]
Cool!
Thank you again!
Just test all works.

**Comment by lexxua** [comment]
Hello, probably typo still exists here:
dist/homer-5.0.1.b1.min.js
and in :
strore/dashboard/_1431943495.json
store/dashboard/_1426001444630.json

**Comment by adubovikov** [comment]
https://github.com/sipcapture/homer-ui/commit/0dee39e236d07aca4b8bb1f173262781cac4840d
